// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Template__Html$RescriptStatic = require("./Template__Html.bs.js");

function Template__BlogIndex$BlogPost(Props) {
  var blogPost = Props.blogPost;
  return React.createElement("p", undefined, React.createElement("a", {
                  href: blogPost.id + ".html"
                }, blogPost.title), React.createElement("br", undefined), React.createElement("span", undefined, blogPost.date.toDateString()));
}

var BlogPost = {
  make: Template__BlogIndex$BlogPost
};

function Template__BlogIndex(Props) {
  var blogPosts = Props.blogPosts;
  var title = "ReScript Static";
  return React.createElement(Template__Html$RescriptStatic.make, {
              title: title,
              children: null
            }, React.createElement("p", undefined, React.createElement("a", {
                      href: "about.html"
                    }, "About this site →")), React.createElement("h1", undefined, title), blogPosts.map(function (blogPost) {
                  return React.createElement(Template__BlogIndex$BlogPost, {
                              blogPost: blogPost,
                              key: blogPost.id
                            });
                }));
}

var make = Template__BlogIndex;

exports.BlogPost = BlogPost;
exports.make = make;
/* react Not a pure module */
