// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var BlogIndex;

var BlogPost;

var Page;

exports.BlogIndex = BlogIndex;
exports.BlogPost = BlogPost;
exports.Page = Page;
/* No side effect */
