// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MarkdownJs = require("./Markdown.js");

var markdown = MarkdownJs;

function render(content) {
  return markdown.render(content);
}

exports.markdown = markdown;
exports.render = render;
/* markdown Not a pure module */
