// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pages = require("./modules/Pages.bs.js");
var React = require("react");
var Template__Page = require("./templates/Template__Page.bs.js");
var Template__BlogPost = require("./templates/Template__BlogPost.bs.js");
var Template__BlogIndex = require("./templates/Template__BlogIndex.bs.js");
var ServerJs = require("react-dom/server.js");

var outputDir = "./docs";

function blogIndex(blogPosts) {
  var el = React.createElement(Template__BlogIndex.make, {
        blogPosts: blogPosts
      });
  return "<!doctype html>" + ServerJs.renderToString(el);
}

function blogPost(blogPost$1) {
  var el = React.createElement(Template__BlogPost.make, {
        blogPost: blogPost$1
      });
  return "<!doctype html>" + ServerJs.renderToString(el);
}

function page(page$1) {
  var el = React.createElement(Template__Page.make, {
        page: page$1
      });
  return "<!doctype html>" + ServerJs.renderToString(el);
}

function makeBlog(param) {
  return Pages.createBlog("./content/posts", outputDir, "index", blogPost, blogIndex);
}

function makePages(param) {
  return Pages.createPages("./content/pages", outputDir, page);
}

function make(param) {
  var __x = Pages.cleanDirectory(outputDir);
  var __x$1 = __x.then(makeBlog);
  return __x$1.then(makePages);
}

exports.make = make;
/* Pages Not a pure module */
