// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Server = require("react-dom/server");
var Pages$RescriptStatic = require("./modules/Pages.bs.js");
var Template__Page$RescriptStatic = require("./templates/Template__Page.bs.js");
var Template__BlogPost$RescriptStatic = require("./templates/Template__BlogPost.bs.js");
var Template__BlogIndex$RescriptStatic = require("./templates/Template__BlogIndex.bs.js");

var outputDir = "./docs";

function blogIndex(blogPosts) {
  var el = React.createElement(Template__BlogIndex$RescriptStatic.make, {
        blogPosts: blogPosts
      });
  return "<!doctype html>" + Server.renderToString(el);
}

function blogPost(blogPost$1) {
  var el = React.createElement(Template__BlogPost$RescriptStatic.make, {
        blogPost: blogPost$1
      });
  return "<!doctype html>" + Server.renderToString(el);
}

function page(page$1) {
  var el = React.createElement(Template__Page$RescriptStatic.make, {
        page: page$1
      });
  return "<!doctype html>" + Server.renderToString(el);
}

function makeBlog(param) {
  return Pages$RescriptStatic.createBlog("./content/posts", outputDir, "index", blogPost, blogIndex);
}

function makePages(param) {
  return Pages$RescriptStatic.createPages("./content/pages", outputDir, page);
}

function make(param) {
  var __x = Pages$RescriptStatic.cleanDirectory(outputDir);
  var __x$1 = __x.then(makeBlog);
  return __x$1.then(makePages);
}

exports.make = make;
/* react Not a pure module */
